//
//  AddNewEpisodeInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import CodableAlamofire

final class AddNewEpisodeInteractor {
}

// MARK: - Extensions -

extension AddNewEpisodeInteractor: AddNewEpisodeInteractorInterface {
    func uploadEpisode(showID: String, episodeTitle: String, seasonNumber: String, episodeNumber: String, episodeDescription: String, episodeMediaID: String, completion: @escaping (Result<ShowDetails>) -> ()) {
        guard
            let token = NetworkManager.loginData?.token
            else {
                return
        }
        let headers = ["Authorization": token]
        let parameters = ["showId": showID,
                          "mediaId": episodeMediaID,
                          "title": episodeTitle,
                          "description": episodeDescription,
                          "episodeNumber": episodeNumber,
                          "season" : seasonNumber]

        Alamofire
            .request("https://api.infinum.academy/api/episodes",
                method: .post,
                parameters: parameters,
                encoding: JSONEncoding.default,
                headers: headers)
            .validate()
            .responseDecodableObject(keyPath: "data", decoder: JSONDecoder()) { response in
                completion(response.result)
        }
    }


    
}
