//
//  AddNewEpisodePresenter.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddNewEpisodePresenter {

    // MARK: - Private properties -

    private unowned var _view: AddNewEpisodeViewInterface
    private var _interactor: AddNewEpisodeInteractorInterface
    private var _wireframe: AddNewEpisodeWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: AddNewEpisodeWireframeInterface, view: AddNewEpisodeViewInterface, interactor: AddNewEpisodeInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension AddNewEpisodePresenter: AddNewEpisodePresenterInterface {

    func didPressBackButton() {
        _wireframe.navigate(to: .showDetails)
    }

    func didPressAddButton() {
        
    }

}
