//
//  AddNewEpisodeViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddNewEpisodeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: AddNewEpisodePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configureNavigationBar()
    }


    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }

    private func configureNavigationBar() {
        self.title = "Add Episode"
        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        navigationItem.leftBarButtonItem = UIBarButtonItem(title: "Cancel",
                                                           style: .plain,
                                                           target: self,
                                                           action: #selector(didSelectCancel))
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Add",
                                                            style: .plain,
                                                            target: self,
                                                            action: #selector(didSelectAdd))
    }

    // MARK: - @objc functions
    @objc func didSelectCancel() {
        presenter.didPressBackButton()
    }

    @objc func didSelectAdd() {
        presenter.didPressAddButton()
    }

}

// MARK: - Extensions -

extension AddNewEpisodeViewController: AddNewEpisodeViewInterface {
}
