//
//  AddNewEpisodeViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddNewEpisodeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: AddNewEpisodePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }


    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
	
}

// MARK: - Extensions -

extension AddNewEpisodeViewController: AddNewEpisodeViewInterface {
}
