//
//  AddNewEpisodeWireframe.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddNewEpisodeWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "AddNewEpisode", bundle: nil)

    // MARK: - Module setup -

    init(show: Show) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: AddNewEpisodeViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = AddNewEpisodeInteractor()
        let presenter = AddNewEpisodePresenter(wireframe: self, view: moduleViewController, interactor: interactor, show: show)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension AddNewEpisodeWireframe: AddNewEpisodeWireframeInterface {

    func navigate(to option: AddNewEpisodeNavigationOption) {

        switch option {
        case .showDetails:
            _returnToShowDetails()
        }

    }

    private func _returnToShowDetails() {
        navigationController?.popViewController(animated: true)
    }
}
