//
//  AddNewEpisodePresenter.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AddNewEpisodePresenter {

    // MARK: - Private properties -

    private unowned var _view: AddNewEpisodeViewInterface
    private var _interactor: AddNewEpisodeInteractorInterface
    private var _wireframe: AddNewEpisodeWireframeInterface
    private var _show: Show
    

    // MARK: - Lifecycle -

    init(wireframe: AddNewEpisodeWireframeInterface, view: AddNewEpisodeViewInterface, interactor: AddNewEpisodeInteractorInterface, show: Show) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        _show = show
    }
}

// MARK: - Extensions -

extension AddNewEpisodePresenter: AddNewEpisodePresenterInterface {

    func didPressBackButton() {
        _wireframe.navigate(to: .showDetails)
    }

    func didPressAddButton(episodeTitle: String, seasonNumber: String, episodeNumber: String, episodeDescription: String) {
        _interactor.uploadEpisode(showID: _show.id, episodeTitle: episodeTitle, seasonNumber: seasonNumber, episodeNumber: episodeNumber, episodeDescription: episodeDescription, episodeMediaID: "") { result in

            switch result {
            case .success(let response):
                    print (response)
                    self._wireframe.navigate(to: .showDetails)
            case .failure(let error):
                    print (error)
            }
        }
    }

}
