//
//  CommentsPresenter.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CommentsPresenter {

    // MARK: - Private properties -

    private unowned var _view: CommentsViewInterface
    private var _interactor: CommentsInteractorInterface
    private var _wireframe: CommentsWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: CommentsWireframeInterface, view: CommentsViewInterface, interactor: CommentsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension CommentsPresenter: CommentsPresenterInterface {
}
