//
//  CommentsWireframe.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CommentsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Comments", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: CommentsViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = CommentsInteractor()
        let presenter = CommentsPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CommentsWireframe: CommentsWireframeInterface {

    func navigate(to option: CommentsNavigationOption) {
    }
}
