# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'SVProgressHUD', '~> 2.2'
  # Pod for Networking
  pod 'Alamofire', '~> 4.7'
  # Coder and decoder for json
  pod 'CodableAlamofire', '~> 1.1'
  # library for downloading and caching images from the web
  pod 'Kingfisher', '~> 4.8'
  # pod for simplifying usage of keychain
  pod 'KeychainAccess', '~> 3.1'
  #pod for animations
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

end
