//
//  HomeInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import CodableAlamofire

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {

    func fetchShows(completion: @escaping (Result<[Show]>) -> ()) {
        guard
            let token = NetworkManager.loginData?.token
            else {
                return
        }
        let headers = ["Authorization": token]

        Alamofire
            .request("https://api.infinum.academy/api/shows",
                          method: .get,
                          parameters: nil,
                          encoding: JSONEncoding.default,
                          headers: headers)
            .validate()
            .responseDecodableObject(keyPath: "data", decoder: JSONDecoder()) { response in
                    completion(response.result)

        }
    }

}
