//
//  HomeWireframe.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Home", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: HomeViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = HomeInteractor()
        let presenter = HomePresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {

    func navigate(to option: HomeNavigationOption) {
        switch option {
            case .login:
            _goToLogin()
            case .showDetails(let show):
            _goToShowDetails(show: show)
        }

    }

    private func _goToLogin() {
        navigationController?.popViewController(animated: true)
    }

    private func _goToShowDetails(show: Show) {

        let wireframe = ShowDetailsWireframe(show: show)

        navigationController?.pushWireframe(wireframe)
    }
}
