//
//  HomeInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum HomeNavigationOption {
    case login
}

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
    func reloadData()
}

protocol HomePresenterInterface: PresenterInterface {
    func didPressLogout()
    func numberOfRowsInSection() -> Int
    func getShow(at index: Int) -> Show
    func removeShow(at index: Int)
}

protocol HomeInteractorInterface: InteractorInterface {
    func fetchShows(completion: @escaping (Result<[Show]>) -> ())
}
