//
//  LoginInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum LoginNavigationOption {
    case home
}

protocol LoginWireframeInterface: WireframeInterface {
    func navigate(to option: LoginNavigationOption)
}

protocol LoginViewInterface: ViewInterface {
}

protocol LoginPresenterInterface: PresenterInterface {
    func didSelectLoginAction(with email: String?, password: String?)
    func didSelectCreateAnAccountAction(with email: String?, password: String?)
    func didPressRememberMe()
}

protocol LoginInteractorInterface: InteractorInterface {
}
