//
//  LoginViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit


final class LoginViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    @IBOutlet private weak var emailTextField: UITextField!
    @IBOutlet private weak var passwordTextField: UITextField!

    @IBOutlet private weak var rememberMeButton: UIButton!
    @IBOutlet private weak var loginButton: UIButton!
    @IBOutlet private weak var createAnAccountButton: UIButton!


    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }

    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
    }

    // MARK: Actions

    @IBAction func _loginButtonActionHandler(_ sender: Any) {
        presenter.didSelectLoginAction(with: emailTextField.text, password: passwordTextField.text)
    }

    @IBAction func _createAnAccountActionHandler(_ sender: Any) {
        presenter.didSelectCreateAnAccountAction(with: emailTextField.text, password: passwordTextField.text)
    }
    @IBAction func _rememberMeButtonActionHandler(_ sender: Any) {

    }
    
    

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}
