//
//  LoginPresenter.swift
//  TVShows
//
//  Created by Ivan Milicevic on 18/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPresenter {

    // MARK: - Private properties -

    private unowned var _view: LoginViewInterface
    private var _interactor: LoginInteractorInterface
    private var _wireframe: LoginWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {

    func didSelectLoginAction(with email: String?, password: String?) {
        guard let email = email, let password = password else {
            return
        }
        _view.showProgressHUD()
        _interactor.loginUser(with: email, password: password) { result in



            switch result {
            case .success(let loginData):
                    self._view.hideProgressHUD()
                    self._wireframe.navigate(to: .home)
            case .failure(let error):
                    self._view.hideProgressHUD()
                    //TODO
            }
        }


    }

    func didSelectCreateAnAccountAction(with email: String?, password: String?) {
        guard let _email = email, let _password = password else {
            return
        }
        print(_email + _password)

    }

    func didPressRememberMe() {

    }
}
