//
//  ShowDetailsViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ShowDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ShowDetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension ShowDetailsViewController: ShowDetailsViewInterface {
}
