//
//  ShowDetailsInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ShowDetailsInteractor {
}

// MARK: - Extensions -

extension ShowDetailsInteractor: ShowDetailsInteractorInterface {
}
