//
//  ShowDetailsInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import CodableAlamofire

enum ShowDetailsNavigationOption {
    case home
}

protocol ShowDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: ShowDetailsNavigationOption)
}

protocol ShowDetailsViewInterface: ViewInterface {
}

protocol ShowDetailsPresenterInterface: PresenterInterface {
    func didPressBackButton()
}

protocol ShowDetailsInteractorInterface: InteractorInterface {
    func fetchShowDetails(show: Show, completion: @escaping (Result<ShowDetails>) -> ())
    func fetchEpisodes(show: Show, completion: @escaping (Result<[ShowEpisode]>) -> ())
}
