//
//  ShowDetailsInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import CodableAlamofire

final class ShowDetailsInteractor {
}

// MARK: - Extensions -

extension ShowDetailsInteractor: ShowDetailsInteractorInterface {
    func fetchShowDetails(show: Show, completion: @escaping (Result<ShowDetails>) -> ()) {
        guard
            let token = NetworkManager.loginData?.token
            else {
                return
        }
        let headers = ["Authorization": token]

        Alamofire
            .request("https://api.infinum.academy/api/shows/\(show.id)",
                     method: .get,
                     parameters: nil,
                     encoding: JSONEncoding.default,
                     headers: headers)
            .validate()
            .responseDecodableObject(keyPath: "data", decoder: JSONDecoder()) { response in
                completion(response.result)
        }
    }

    func fetchEpisodes(show: Show, completion: @escaping (Result<[ShowEpisode]>) -> ()) {
        guard
            let token = NetworkManager.loginData?.token
            else {
                return
        }
        let headers = ["Authorization": token]

        Alamofire
            .request("https://api.infinum.academy/api/shows/\(show.id)/episodes",
                     method: .get,
                     parameters: nil,
                     encoding: JSONEncoding.default,
                     headers: headers)
            .validate()
            .responseDecodableObject(keyPath: "data", decoder: JSONDecoder()) { response in
                completion(response.result)

        }
    }

    
}
