//
//  ShowDetailsInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ShowDetailsNavigationOption {
}

protocol ShowDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: ShowDetailsNavigationOption)
}

protocol ShowDetailsViewInterface: ViewInterface {
}

protocol ShowDetailsPresenterInterface: PresenterInterface {
}

protocol ShowDetailsInteractorInterface: InteractorInterface {
}
