//
//  ShowDetailsInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 22/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import CodableAlamofire

enum ShowDetailsNavigationOption {
    case home
    case addNewEpisode(show: Show)
    case episodeDetails(episode: ShowEpisode)
}

protocol ShowDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: ShowDetailsNavigationOption)
}

protocol ShowDetailsViewInterface: ViewInterface {
    func reloadData()
}

protocol ShowDetailsPresenterInterface: PresenterInterface {
    func didPressBackButton()
    func didPressAddNewEpisodeButton()
    func getShowDetails() -> ShowDetails?
    func getEpisodesCount() -> Int
    func numberOfRowsInSection() -> Int
    func getEpisode(at index: Int) -> ShowEpisode
    func removeEpisode(at index: Int)
    func didSelectEpisode(at index: Int)
    func reloadData()
}

protocol ShowDetailsInteractorInterface: InteractorInterface {
    func fetchShowDetails(show: Show, completion: @escaping (Result<ShowDetails>) -> ())
    func fetchEpisodes(show: Show, completion: @escaping (Result<[ShowEpisode]>) -> ())
}
