//
//  EpisodeDetailsInterfaces.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum EpisodeDetailsNavigationOption {
    case showDetails
    case comments
}

protocol EpisodeDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: EpisodeDetailsNavigationOption)
}

protocol EpisodeDetailsViewInterface: ViewInterface {
}

protocol EpisodeDetailsPresenterInterface: PresenterInterface {
}

protocol EpisodeDetailsInteractorInterface: InteractorInterface {
    func fetchEpisodeDetails(episode: ShowEpisode, completion: @escaping (Result<EpisodeDetails>) -> ())
    
}
