//
//  EpisodeDetailsInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EpisodeDetailsInteractor {
}

// MARK: - Extensions -

extension EpisodeDetailsInteractor: EpisodeDetailsInteractorInterface {
}
