//
//  EpisodeDetailsPresenter.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EpisodeDetailsPresenter {

    // MARK: - Private properties -

    private unowned var _view: EpisodeDetailsViewInterface
    private var _interactor: EpisodeDetailsInteractorInterface
    private var _wireframe: EpisodeDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: EpisodeDetailsWireframeInterface, view: EpisodeDetailsViewInterface, interactor: EpisodeDetailsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension EpisodeDetailsPresenter: EpisodeDetailsPresenterInterface {
}
