//
//  EpisodeDetailsInteractor.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import CodableAlamofire

final class EpisodeDetailsInteractor {
}

// MARK: - Extensions -

extension EpisodeDetailsInteractor: EpisodeDetailsInteractorInterface {

    func fetchEpisodeDetails(episode: ShowEpisode, completion: @escaping (Result<EpisodeDetails>) -> ()) {
        guard
            let token = NetworkManager.loginData?.token
            else {
                return
        }
        let headers = ["Authorization": token]

        Alamofire
            .request("https://api.infinum.academy/api/episodes/\(episode.id)",
                     method: .get,
                     parameters: nil,
                     encoding: JSONEncoding.default,
                     headers: headers)
            .validate()
            .responseDecodableObject(keyPath: "data", decoder: JSONDecoder()) { response in
                completion(response.result)
        }
    }

}
