//
//  EpisodeDetailsViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EpisodeDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: EpisodeDetailsPresenterInterface!

    // MARK: - Private properties -

    @IBOutlet private weak var imageView: UIImageView!
    @IBOutlet private weak var episodeTitleLabel: UILabel!
    @IBOutlet private weak var episodeSeasonAndEpisodeLabel: UILabel!
    @IBOutlet private weak var episodeDescriptionLabel: UILabel!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }

    @IBAction func didPressBackButton(_ sender: Any) {
        presenter.didPressBackButton()
    }

    @IBAction func didPressCommentsButton(_ sender: Any) {
        presenter.didPressCommentsButton()
    }

	
}

// MARK: - Extensions -

extension EpisodeDetailsViewController: EpisodeDetailsViewInterface {

    func reloadData(episodeDetails: EpisodeDetails) {
        print(episodeDetails)
        episodeTitleLabel.text = episodeDetails.title
        episodeSeasonAndEpisodeLabel.text = "S\(episodeDetails.season) E\(episodeDetails.episodeNumber)"
        episodeDescriptionLabel.text = episodeDetails.description
    }

}
