//
//  EpisodeDetailsViewController.swift
//  TVShows
//
//  Created by Ivan Milicevic on 23/10/2018.
//  Copyright (c) 2018 Ivan Milicevic. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EpisodeDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: EpisodeDetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension EpisodeDetailsViewController: EpisodeDetailsViewInterface {
}
